[project]
name = "prs-med-mmrs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "accelerate>=1.10.1",
    "albumentations>=2.0.8",
    "numpy>=2.0.2",
    "peft>=0.17.1",
    "pytest>=8.4.2",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.6.1",
    "segmentation-models-pytorch>=0.5.0",
    "timm>=1.0.21",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
    "transformers>=4.57.1",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
prs-med-mmrs = { workspace = true }

[dependency-groups]
dev = [
    "prs-med-mmrs",
]
